version: "3.9"
services:
  goapi:
    build: .
    ports:
      - "5000:3000"
    restart: always
    links:
      - postgresgo
  postgresgo:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=newt
      - POSTGRES_DB=gorm
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # mongo -> /data/db
      # mysql -> /var/lib/mysql

volumes:
  postgres-data:
